version: '3.8'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes: 
      - ./movie_service:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://test_user1:testpass1234@movies_db:5432/movies_db
      - CASTS_SERVICE_HOST_URL=http://nginx:8080/api/v1/casts/
    depends_on:
      - movies_db
      - cast_service

  movies_db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user1
      - POSTGRES_PASSWORD=testpass1234
      - POSTGRES_DB=movies_db

  cast_service:
    build: ./cast_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service:/app/
    ports:
      - 8002:8000
    environment:
      - CASTS_DATABASE_URI=postgresql://test_user1:testpass1234@casts_db:5432/casts_db
    depends_on:
      - casts_db

  casts_db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user1
      - POSTGRES_PASSWORD=testpass1234
      - POSTGRES_DB=casts_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    depends_on:
      - movie_service
      - cast_service

volumes:
  postgres_data_movie:
  postgres_data_cast: